### ISSUE TITLE
Script failed after one conversion with divide by zero error (Audible library of 1212 files)

### ISSUE THREAD

**Issue by riwide** [orbitalteapot/OpenAudible-FileOrganizer#10]
Tried to convert my library under Windows, from network share mapped to Z:
I suspect my library is too large (CSV file size)

**Comment by riwide** [comment]
I tested under Windows with a library of 33 books and it works fine. 
Made me wonder if the visual progress bar doesnt scale correctly with a large number of files, perhapsd exceeding an array size or string length.

**Comment by orbitalteapot** [comment]
Try now :)
