### ISSUE TITLE
Skipping row due to inconsistent data:

### ISSUE THREAD

**Issue by taisau** [orbitalteapot/OpenAudible-FileOrganizer#8]
**Describe the bug**
"Skipping row due to inconsistent data"

**To Reproduce**
run the exe

**Expected behavior**
move files to respective folders

**Additional context**
Using export.json, one file is successfully moved out of 110.

**Comment by orbitalteapot** [comment]
Thanks for reporting!

I'm working on a fix after multiple bugs appeared after the latest release from OpenAudible.

Hopefully, I will have a fix/release ready by 06.Nov

**Comment by hardybm** [comment]
Keen as well. Thank you.

**Comment by hardybm** [comment]
> Keen as well. Thank you.

Looks like a format change in the CSV. There are no longer 34 elements. 

```
def load_books(csv_file):
    books = []
    with open(csv_file, 'r', encoding='utf-8-sig') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        for row in reader:
            if len(row) == 34:
                books.append(Book(*row))
            else:
                print(f"Skipping row due to inconsistent data: {row}")
    return books
```

**Comment by hardybm** [comment]
Editing the books.csv to remove the "File paths" and "PDF" columns allows the script to proceed to the next level however then fails out with "Unexpected error: No tag reader found to support filetype!"

I'm using the docker version and my files are M4B

**Comment by orbitalteapot** [comment]
Sorry about the long delay, exams took all my time.

Trying remedy the issues with an dynamic mapping from the csv file.

**Comment by orbitalteapot** [comment]
Created a new release. The console version is available under release.
Docker, and service version within the following weeks.
