### ISSUE TITLE
Failed from Linux with network share of audible files mounted locally (e.g. ~/audio )

### ISSUE THREAD

**Issue by riwide** [orbitalteapot/OpenAudible-FileOrganizer#9]
The 3 file paths failed:
~/audio/2023-OpenAudible/books   (an open audible conversion of aax files to m4b)
~/audio/2023-OpenAudible/books.csv
~/audio/2023-OpenAudible/books/jellyfin 

I assume it might want a drive letter, since I managed to progress further under windows

**Comment by orbitalteapot** [comment]
The new version handles the difference between Windows and Linux file paths better :)
